name: Reanna Joseph
favicon: null
layout_spectrum: 1
typography_spectrum: 0.88145
title: Reanna Joseph
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a1910'
    - '#ffffff'
    - '#c73056'
    - '#a1975b'
    - '#687322'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
