name: Reanna Joseph
favicon: null
layout_spectrum: 0.21278969082050025
typography_spectrum: 0.6659688393119723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.219800328835845
  lightness: 0.9536076902877539
  saturation: 0.43281074799597263
  rhythmicContrast: 0.6516388149466366
purpose: []
